markdown: kramdown
highlighter: pygments
permalink: /posts/:title
rdiscount:
  extensions: [smart]
exclude: [ Gemfile, Gemfile.lock, gems, _assets, bower_components ]
title: Joe's Mots
production_url: "http://www.joekearney.co.uk"
description: "Trying to be cogent."
analytics: UA-49379324-1
#disqus: on
#gauges: 50f2b533613f5d7c8000000c
author :
  name : Joe Kearney
  github : joekearney
  twitter : joejkearney
  email: mail@joekearney.co.uk


####
#### To add a new tag:
#### - add to enumerable-tags
#### - add an index page
####
#### To rename a tag:
#### - change the tag_name here
#### - change the title of the index page for that tag
####
enumerable-tags:
- honeyment
- tasty-rsvps
- germany
- article

article:
  tag_description: "Trying to be cogent"
  tag_name: "Joe's Mots on Software"
  index_path: "article-index"
honeyment:
  tag_description: "Post-engagement pre-honeymoon adventure"
  tag_name: "Honeyment"
  index_path: "honeyment-index"
tasty-rsvps:
  tag_description: "Our wedding guest book of recipes"
  tag_name: "Tasty RSVP"
  website_link: http://www.joandjoegetmarried.co.uk/#!rsvp
  index_path: "tasty-rsvps-index"
germany:
  tag_name: "Das Jo(e)"
  tag_description: "The Jo(e)s Fighting German Bureaucracy Since 2015"
  index_path: "germany-index"
