permalink: /posts/:title
rdiscount:
  extensions: [smart]
highlighter: rouge
exclude: [ Gemfile, Gemfile.lock, gems, _assets, bower_components ]
timezone: Europe/Berlin
title: "Joe’s Mots"
production_url: "http://www.joekearney.co.uk"
description: "Trying to be cogent."
analytics: UA-49379324-1
#disqus: on
#gauges: 50f2b533613f5d7c8000000c
author :
  name : Joe Kearney
  github : joekearney
  twitter : joejkearney

empty_array: []

# series specific properties
haute_route_stage_home_page: http://www.hauteroute.org/events/view-stage/stage-1-alps-2017

####
#### To add a new tag:
#### - add to enumerable-tags
#### - add an index page
####
#### To rename a tag:
#### - change the tag_name here
#### - change the title of the index page for that tag
####
enumerable-tags:
- honeyment
- tasty-rsvps
- germany
- software
- just-in-time

hidden_tags:
- article
- draft
- hasIndexPage
- isIndexRoot
- tasty-rsvps-savoury
- tasty-rsvps-sweet
- wedding
- comments
- nocomments

# software posts that are to be read, not just howto
software:
  tag_description: "Trying to be cogent"
  tag_name: "Joe’s Mots on Software"
  tag_short_name: "Software"
  index_path: "software-index"
honeyment:
  tag_description: "Post-engagement pre-honeymoon adventure"
  tag_name: "Honeyment"
  tag_short_name: "Honeyment"
  index_path: "honeyment-index"
tasty-rsvps:
  tag_description: "Our wedding guest book of recipes"
  tag_name: "Tasty RSVP"
  tag_short_name: "Tasty RSVP"
  website_link: http://www.joandjoegetmarried.co.uk/#!rsvp
  index_path: "tasty-rsvps-index"
cycling:
  tag_description: "Two wheeled adventures"
  tag_name: "Cycling"
  tag_short_name: "Cycling"
germany:
  tag_name: "Das Jo(e)"
  tag_short_name: "Germany"
  tag_description: "The Jo(e)s Fighting German Bureaucracy Since 2015"
  index_path: "germany-index"
just-in-time:
  tag_name: "Just In Time"
  index_path: "just-in-time"
haute-route:
  tag_name: "Haute Route Alps 2017"
  tag_short_name: "Haute Route"
  index_path: "haute-route"
