markdown: kramdown
highlighter: pygments
permalink: /posts/:title
rdiscount:
  extensions: [smart]
exclude: [ Gemfile, Gemfile.lock, gems, _assets, bower_components ]
title : Joe's Mots
production_url : http://www.joekearney.co.uk
description: "Trying to be cogent."
analytics: UA-49379324-1
#disqus: on
#gauges: 50f2b533613f5d7c8000000c
author :
  name : Joe Kearney
  github : joekearney
  twitter : joejkearney
  email: mail@joekearney.co.uk

enumerable-tags:
- honeyment
- tasty-rsvps
- germany

honeyment:
  tag_description: "Post-engagement pre-honeymoon adventure"
  tag_name: "Honeyment"
tasty-rsvps:
  tag_description: "Our wedding guest book of recipes"
  website_link: http://www.joandjoegetmarried.co.uk/#!rsvp
  tag_name: "Tasty RSVPs"
germany:
  tag_name: "Ich Bin Ein Berliner"
  description: "The Jo(e)s Fighting Bureaucracy Since 2015"
